//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.20 at 01:17:40 PM MSK 
//


package by.teachmeskills.springbootproject.soap.model;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for nationality.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="nationality"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Britain"/&gt;
 *     &lt;enumeration value="America"/&gt;
 *     &lt;enumeration value="India"/&gt;
 *     &lt;enumeration value="Belarus"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "nationality")
@XmlEnum
public enum Nationality {

    @XmlEnumValue("Britain")
    BRITAIN("Britain"),
    @XmlEnumValue("America")
    AMERICA("America"),
    @XmlEnumValue("India")
    INDIA("India"),
    @XmlEnumValue("Belarus")
    BELARUS("Belarus");
    private final String value;

    Nationality(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Nationality fromValue(String v) {
        for (Nationality c: Nationality.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
