//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.20 at 01:17:40 PM MSK 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "https:///www.baeldung.com/springsoap/gen", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.teachmeskills.springbootproject.soap.model;
