//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.20 at 01:17:40 PM MSK 
//


package by.teachmeskills.springbootproject.soap.model;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


/**
 * <p>Java class for student complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="student"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="course" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="averageGrade" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nationality" type="{http://www.baeldung.com/springsoap/gen}nationality"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "student", propOrder = {
    "name",
    "course",
    "averageGrade",
    "nationality"
})
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
public class Student {

    @XmlElement(required = true)
    protected String name;
    protected int course;
    @XmlElement(required = true)
    protected double averageGrade;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Nationality nationality;
}
