/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

USE [exploration]

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_computers_rooms]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [computers] DROP CONSTRAINT [FK_computers_rooms]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_connections_cities1]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [connections] DROP CONSTRAINT [FK_connections_cities1]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_connections_cities2]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [connections] DROP CONSTRAINT [FK_connections_cities2]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_site_pages_site_pages]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [site_pages] DROP CONSTRAINT [FK_site_pages_site_pages]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[cities]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [cities]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[computers]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [computers]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[connections]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [connections]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dates]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dates]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[library_in_json]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [library_in_json]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[overflow]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [overflow]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[rooms]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [rooms]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[shopping]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [shopping]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[site_pages]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [site_pages]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[table_with_nulls]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [table_with_nulls]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[test_counts]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [test_counts]
GO

/* Create Tables */

CREATE TABLE [cities]
(
	[ct_id] int NOT NULL IDENTITY (1, 1),
	[ct_name] nvarchar(50) NOT NULL
)
GO

CREATE TABLE [computers]
(
	[c_id] int NOT NULL IDENTITY (1, 1),
	[c_room] int NULL,
	[c_name] nvarchar(50) NOT NULL
)
GO

CREATE TABLE [connections]
(
	[cn_from] int NOT NULL,
	[cn_to] int NOT NULL,
	[cn_cost] money NULL,
	[cn_bidir] char(1) NOT NULL
)
GO

CREATE TABLE [dates]
(
	[d] date NULL
)
GO

CREATE TABLE [library_in_json]
(
	[lij_id] int NOT NULL IDENTITY (1, 1),
	[lij_book] nvarchar(150) NOT NULL,
	[lij_author] nvarchar(2000) NOT NULL,
	[lij_genre] nvarchar(2000) NOT NULL
)
GO

CREATE TABLE [overflow]
(
	[x] int NULL
)
GO

CREATE TABLE [rooms]
(
	[r_id] int NOT NULL IDENTITY (1, 1),
	[r_name] nvarchar(50) NOT NULL,
	[r_space] tinyint NOT NULL
)
GO

CREATE TABLE [shopping]
(
	[sh_id] int NOT NULL IDENTITY (1, 1),
	[sh_transaction] int NOT NULL,
	[sh_category] nvarchar(150) NOT NULL
)
GO

CREATE TABLE [site_pages]
(
	[sp_id] int NOT NULL IDENTITY (1, 1),
	[sp_parent] int NULL,
	[sp_name] nvarchar(200) NULL
)
GO

CREATE TABLE [table_with_nulls]
(
	[x] int NULL
)
GO

CREATE TABLE [test_counts]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[fni] int NULL,
	[fwi] int NULL,
	[fni_nn] int NOT NULL,
	[fwi_nn] int NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [cities] 
 ADD CONSTRAINT [PK_cities]
	PRIMARY KEY CLUSTERED ([ct_id] ASC)
GO

ALTER TABLE [computers] 
 ADD CONSTRAINT [PK_computers]
	PRIMARY KEY CLUSTERED ([c_id] ASC)
GO

ALTER TABLE [connections] 
 ADD CONSTRAINT [PK_connections]
	PRIMARY KEY CLUSTERED ([cn_from] ASC,[cn_to] ASC)
GO

ALTER TABLE [connections] 
 ADD CONSTRAINT [CHK_bidir] CHECK ([cn_bidir] IN ('N','Y'))
GO

CREATE NONCLUSTERED INDEX [idx_d] 
 ON [dates] ([d] ASC)
GO

ALTER TABLE [library_in_json] 
 ADD CONSTRAINT [PK_library_in_json]
	PRIMARY KEY CLUSTERED ([lij_id] ASC)
GO

ALTER TABLE [library_in_json] 
 ADD CONSTRAINT [lij_author_is_JSON] CHECK (ISJSON([lij_author])=1)
GO

ALTER TABLE [library_in_json] 
 ADD CONSTRAINT [lij_genre_is_JSON] CHECK (ISJSON([lij_genre])=1)
GO

ALTER TABLE [rooms] 
 ADD CONSTRAINT [PK_rooms]
	PRIMARY KEY CLUSTERED ([r_id] ASC)
GO

ALTER TABLE [shopping] 
 ADD CONSTRAINT [PK_shopping]
	PRIMARY KEY CLUSTERED ([sh_id] ASC)
GO

ALTER TABLE [site_pages] 
 ADD CONSTRAINT [PK_site_pages]
	PRIMARY KEY CLUSTERED ([sp_id] ASC)
GO

ALTER TABLE [test_counts] 
 ADD CONSTRAINT [PK_test_counts]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

CREATE NONCLUSTERED INDEX [idx_fwi] 
 ON [test_counts] ([fwi] ASC)
GO

CREATE NONCLUSTERED INDEX [idx_fwi_nn] 
 ON [test_counts] ([fwi_nn] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [computers] ADD CONSTRAINT [FK_computers_rooms]
	FOREIGN KEY ([c_room]) REFERENCES [rooms] ([r_id]) ON DELETE Cascade ON UPDATE Cascade
GO

ALTER TABLE [connections] ADD CONSTRAINT [FK_connections_cities1]
	FOREIGN KEY ([cn_from]) REFERENCES [cities] ([ct_id]) ON DELETE Cascade ON UPDATE Cascade
GO

ALTER TABLE [connections] ADD CONSTRAINT [FK_connections_cities2]
	FOREIGN KEY ([cn_to]) REFERENCES [cities] ([ct_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [site_pages] ADD CONSTRAINT [FK_site_pages_site_pages]
	FOREIGN KEY ([sp_parent]) REFERENCES [site_pages] ([sp_id])
GO
