-- MySQL Script generated by MySQL Workbench
-- Sun Oct 15 13:04:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`owner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`owner` ;

CREATE TABLE IF NOT EXISTS `mydb`.`owner` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(90) NOT NULL,
  `lastName` VARCHAR(90) NOT NULL,
  `birthDate` DATE NOT NULL,
  `passportNumber` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`account` ;

CREATE TABLE IF NOT EXISTS `mydb`.`account` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `balance` DECIMAL(19,6) NOT NULL,
  `owner_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_accounts_owner_idx` (`owner_id` ASC) VISIBLE,
  UNIQUE INDEX `owner_id_UNIQUE` (`owner_id` ASC) VISIBLE,
  INDEX `idx_balance` (`balance` ASC) VISIBLE,
  CONSTRAINT `fk_accounts_owner`
    FOREIGN KEY (`owner_id`)
    REFERENCES `mydb`.`owner` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`system_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`system_account` ;

CREATE TABLE IF NOT EXISTS `mydb`.`system_account` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_system_accounts_account1_idx` (`account_id` ASC) VISIBLE,
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_system_accounts_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`account` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`status` ;

CREATE TABLE IF NOT EXISTS `mydb`.`status` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`account_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`account_status` ;

CREATE TABLE IF NOT EXISTS `mydb`.`account_status` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` INT UNSIGNED NOT NULL,
  `status_id` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_account_status_account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_account_status_status1_idx` (`status_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_status_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`account` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_account_status_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `mydb`.`status` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`transaction` ;

CREATE TABLE IF NOT EXISTS `mydb`.`transaction` (
  `id` VARCHAR(90) NOT NULL,
  `sum` DECIMAL(19,6) UNSIGNED NOT NULL,
  `date_time` TIMESTAMP(6) NOT NULL,
  `account_from_id` INT UNSIGNED NOT NULL,
  `account_to_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transaction_account1_idx` (`account_from_id` ASC) VISIBLE,
  INDEX `fk_transaction_account2_idx` (`account_to_id` ASC) VISIBLE,
  UNIQUE INDEX `account_from_id_UNIQUE` (`account_from_id` ASC) VISIBLE,
  UNIQUE INDEX `account_to_id_UNIQUE` (`account_to_id` ASC) VISIBLE,
  INDEX `idx_date_time` (`date_time` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_account1`
    FOREIGN KEY (`account_from_id`)
    REFERENCES `mydb`.`account` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_transaction_account2`
    FOREIGN KEY (`account_to_id`)
    REFERENCES `mydb`.`account` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`country` ;

CREATE TABLE IF NOT EXISTS `mydb`.`country` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`city` ;

CREATE TABLE IF NOT EXISTS `mydb`.`city` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`country_city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`country_city` ;

CREATE TABLE IF NOT EXISTS `mydb`.`country_city` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `country_id` SMALLINT UNSIGNED NOT NULL,
  `city_id` SMALLINT UNSIGNED NOT NULL,
  INDEX `fk_country_has_city_city1_idx` (`city_id` ASC) VISIBLE,
  INDEX `fk_country_has_city_country1_idx` (`country_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_country_has_city_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`country` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_country_has_city_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `mydb`.`city` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`office`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`office` ;

CREATE TABLE IF NOT EXISTS `mydb`.`office` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(90) NOT NULL,
  `efficiency` DECIMAL(4,2) UNSIGNED NOT NULL,
  `location_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_office_country_city1_idx` (`location_id` ASC) VISIBLE,
  INDEX `idx_location_id_efficiency` (`location_id` ASC, `efficiency` ASC) VISIBLE,
  CONSTRAINT `fk_office_country_city1`
    FOREIGN KEY (`location_id`)
    REFERENCES `mydb`.`country_city` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sale` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sale` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_from` TIMESTAMP(6) NOT NULL,
  `date_to` TIMESTAMP(6) NOT NULL,
  `sum` DECIMAL(21,6) UNSIGNED NOT NULL,
  `office_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sales_office1_idx` (`office_id` ASC) VISIBLE,
  CONSTRAINT `fk_sales_office1`
    FOREIGN KEY (`office_id`)
    REFERENCES `mydb`.`office` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`office_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`office_address` ;

CREATE TABLE IF NOT EXISTS `mydb`.`office_address` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(90) NOT NULL,
  `building` VARCHAR(90) NOT NULL,
  `office_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_office1_idx` (`office_id` ASC) VISIBLE,
  UNIQUE INDEX `office_id_UNIQUE` (`office_id` ASC) VISIBLE,
  CONSTRAINT `fk_address_office1`
    FOREIGN KEY (`office_id`)
    REFERENCES `mydb`.`office` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
