-- MySQL Script generated by MySQL Workbench
-- Tue Apr 30 18:26:36 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kursach6_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kursach6_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kursach6_db` DEFAULT CHARACTER SET utf8 ;
USE `kursach6_db` ;

-- -----------------------------------------------------
-- Table `kursach6_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kursach6_db`.`categories` (
                                                          `id` INT NOT NULL AUTO_INCREMENT,
                                                          `name` VARCHAR(50) NOT NULL,
                                                          `imagePath` VARCHAR(50) NOT NULL,
                                                          PRIMARY KEY (`id`),
                                                          INDEX `name_indx` (`name` ASC) VISIBLE)
    ENGINE = InnoDB
    AUTO_INCREMENT = 1
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kursach6_db`.`flyway_schema_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kursach6_db`.`flyway_schema_history` (
                                                                     `installed_rank` INT NOT NULL,
                                                                     `version` VARCHAR(50) NULL DEFAULT NULL,
                                                                     `description` VARCHAR(200) NOT NULL,
                                                                     `type` VARCHAR(20) NOT NULL,
                                                                     `script` VARCHAR(1000) NOT NULL,
                                                                     `checksum` INT NULL DEFAULT NULL,
                                                                     `installed_by` VARCHAR(100) NOT NULL,
                                                                     `installed_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                                     `execution_time` INT NOT NULL,
                                                                     `success` TINYINT(1) NOT NULL,
                                                                     PRIMARY KEY (`installed_rank`),
                                                                     INDEX `flyway_schema_history_s_idx` (`success` ASC) VISIBLE)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kursach6_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kursach6_db`.`users` (
                                                     `id` INT NOT NULL AUTO_INCREMENT,
                                                     `name` VARCHAR(50) NOT NULL,
                                                     `lastName` VARCHAR(50) NOT NULL,
                                                     `email` VARCHAR(90) NOT NULL,
                                                     `birthDate` TIMESTAMP NOT NULL,
                                                     `registrationDate` TIMESTAMP NOT NULL,
                                                     `balance` DECIMAL(26,2) NOT NULL,
                                                     `password` VARCHAR(64) NOT NULL,
                                                     `address` VARCHAR(90) NULL DEFAULT NULL,
                                                     `phoneNumber` VARCHAR(20) NULL DEFAULT NULL,
                                                     PRIMARY KEY (`id`),
                                                     UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
    ENGINE = InnoDB
    AUTO_INCREMENT = 1
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kursach6_db`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kursach6_db`.`orders` (
                                                      `id` INT NOT NULL AUTO_INCREMENT,
                                                      `userId` INT NOT NULL,
                                                      `date` TIMESTAMP(6) NOT NULL,
                                                      `price` DECIMAL(24,2) NOT NULL,
                                                      PRIMARY KEY (`id`),
                                                      INDEX `indx_userId` (`userId` ASC) VISIBLE,
                                                      CONSTRAINT `fk_orders_users`
                                                          FOREIGN KEY (`userId`)
                                                              REFERENCES `kursach6_db`.`users` (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 1
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kursach6_db`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kursach6_db`.`authors` (
                                                       `id` INT NOT NULL AUTO_INCREMENT,
                                                       `name` VARCHAR(50) NOT NULL,
                                                       PRIMARY KEY (`id`),
                                                       UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kursach6_db`.`publishers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kursach6_db`.`publishers` (
                                                          `id` INT NOT NULL AUTO_INCREMENT,
                                                          `name` VARCHAR(50) NOT NULL,
                                                          PRIMARY KEY (`id`),
                                                          UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kursach6_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kursach6_db`.`products` (
                                                        `id` INT NOT NULL AUTO_INCREMENT,
                                                        `name` VARCHAR(50) NOT NULL,
                                                        `description` VARCHAR(350) NOT NULL,
                                                        `category` VARCHAR(50) NOT NULL,
                                                        `price` DECIMAL(22,2) NOT NULL,
                                                        `author` INT NOT NULL,
                                                        `publisher` INT NOT NULL,
                                                        PRIMARY KEY (`id`),
                                                        INDEX `category_index` (`category` ASC) VISIBLE,
                                                        INDEX `fk_products_authors1_idx` (`author` ASC) VISIBLE,
                                                        INDEX `fk_products_publishers1_idx` (`publisher` ASC) VISIBLE,
                                                        CONSTRAINT `fk_products_categories`
                                                            FOREIGN KEY (`category`)
                                                                REFERENCES `kursach6_db`.`categories` (`name`)
                                                                ON UPDATE RESTRICT,
                                                        CONSTRAINT `fk_products_authors`
                                                            FOREIGN KEY (`author`)
                                                                REFERENCES `kursach6_db`.`authors` (`id`)
                                                                ON DELETE NO ACTION
                                                                ON UPDATE NO ACTION,
                                                        CONSTRAINT `fk_products_publishers`
                                                            FOREIGN KEY (`publisher`)
                                                                REFERENCES `kursach6_db`.`publishers` (`id`)
                                                                ON DELETE NO ACTION
                                                                ON UPDATE NO ACTION)
    ENGINE = InnoDB
    AUTO_INCREMENT = 1
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kursach6_db`.`orders_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kursach6_db`.`orders_products` (
                                                               `id` INT NOT NULL AUTO_INCREMENT,
                                                               `orderId` INT NOT NULL,
                                                               `productId` INT NOT NULL,
                                                               PRIMARY KEY (`id`),
                                                               INDEX `indx_orderId` (`orderId` ASC) INVISIBLE,
                                                               INDEX `indx_productId` (`productId` ASC) VISIBLE,
                                                               CONSTRAINT `fk_orders_products_orders`
                                                                   FOREIGN KEY (`orderId`)
                                                                       REFERENCES `kursach6_db`.`orders` (`id`),
                                                               CONSTRAINT `fk_orders_products_products`
                                                                   FOREIGN KEY (`productId`)
                                                                       REFERENCES `kursach6_db`.`products` (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 1
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kursach6_db`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kursach6_db`.`roles` (
                                                     `id` INT NOT NULL AUTO_INCREMENT,
                                                     `name` VARCHAR(50) NOT NULL,
                                                     PRIMARY KEY (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 1
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kursach6_db`.`users_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kursach6_db`.`users_roles` (
                                                           `id` INT NOT NULL AUTO_INCREMENT,
                                                           `userId` INT NOT NULL,
                                                           `roleId` INT NOT NULL,
                                                           PRIMARY KEY (`id`),
                                                           INDEX `fk_users_roles_users` (`userId` ASC) VISIBLE,
                                                           INDEX `fk_users_roles_roles` (`roleId` ASC) VISIBLE,
                                                           CONSTRAINT `fk_users_roles_roles`
                                                               FOREIGN KEY (`roleId`)
                                                                   REFERENCES `kursach6_db`.`roles` (`id`),
                                                           CONSTRAINT `fk_users_roles_users`
                                                               FOREIGN KEY (`userId`)
                                                                   REFERENCES `kursach6_db`.`users` (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 1
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kursach6_db`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kursach6_db`.`inventory` (
                                                         `id` INT NOT NULL AUTO_INCREMENT,
                                                         `amount` INT UNSIGNED NOT NULL,
                                                         `productId` INT NOT NULL,
                                                         PRIMARY KEY (`id`),
                                                         INDEX `fk_inventory_products1_idx` (`productId` ASC) VISIBLE,
                                                         UNIQUE INDEX `product_id_UNIQUE` (`productId` ASC) VISIBLE,
                                                         CONSTRAINT `fk_inventory_products`
                                                             FOREIGN KEY (`productId`)
                                                                 REFERENCES `kursach6_db`.`products` (`id`)
                                                                 ON DELETE NO ACTION
                                                                 ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kursach6_db`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kursach6_db`.`suppliers` (
                                                         `id` INT NOT NULL AUTO_INCREMENT,
                                                         `name` VARCHAR(45) NOT NULL,
                                                         PRIMARY KEY (`id`),
                                                         UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kursach6_db`.`inventory_suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kursach6_db`.`inventory_suppliers` (
                                                                   `id` INT NOT NULL AUTO_INCREMENT,
                                                                   `inventoryId` INT NOT NULL,
                                                                   `supplierId` INT NOT NULL,
                                                                   PRIMARY KEY (`id`),
                                                                   INDEX `fk_inventory_suppliers_inventory_idx` (`inventoryId` ASC) VISIBLE,
                                                                   INDEX `fk_inventory_suppliers_suppliers_idx` (`supplierId` ASC) VISIBLE,
                                                                   CONSTRAINT `fk_inventory_suppliers_inventory`
                                                                       FOREIGN KEY (`inventoryId`)
                                                                           REFERENCES `kursach6_db`.`inventory` (`id`)
                                                                           ON DELETE NO ACTION
                                                                           ON UPDATE NO ACTION,
                                                                   CONSTRAINT `fk_inventory_suppliers_suppliers`
                                                                       FOREIGN KEY (`supplierId`)
                                                                           REFERENCES `kursach6_db`.`suppliers` (`id`)
                                                                           ON DELETE NO ACTION
                                                                           ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kursach6_db`.`labels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kursach6_db`.`labels` (
                                                      `id` INT NOT NULL AUTO_INCREMENT,
                                                      `name` VARCHAR(50) NOT NULL,
                                                      PRIMARY KEY (`id`),
                                                      UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kursach6_db`.`products_labels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kursach6_db`.`products_labels` (
                                                               `id` INT NOT NULL AUTO_INCREMENT,
                                                               `productId` INT NOT NULL,
                                                               `labelId` INT NOT NULL,
                                                               PRIMARY KEY (`id`),
                                                               INDEX `fk_products_labels_products1_idx` (`productId` ASC) VISIBLE,
                                                               INDEX `fk_products_labels_labels1_idx` (`labelId` ASC) VISIBLE,
                                                               CONSTRAINT `fk_products_labels_products1`
                                                                   FOREIGN KEY (`productId`)
                                                                       REFERENCES `kursach6_db`.`products` (`id`)
                                                                       ON DELETE NO ACTION
                                                                       ON UPDATE NO ACTION,
                                                               CONSTRAINT `fk_products_labels_labels1`
                                                                   FOREIGN KEY (`labelId`)
                                                                       REFERENCES `kursach6_db`.`labels` (`id`)
                                                                       ON DELETE NO ACTION
                                                                       ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kursach6_db`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kursach6_db`.`images` (
                                                      `id` INT NOT NULL AUTO_INCREMENT,
                                                      `path` VARCHAR(150) NOT NULL,
                                                      PRIMARY KEY (`id`),
                                                      UNIQUE INDEX `path_UNIQUE` (`path` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kursach6_db`.`products_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kursach6_db`.`products_images` (
                                                               `id` INT NOT NULL AUTO_INCREMENT,
                                                               `productId` INT NOT NULL,
                                                               `imageId` INT NOT NULL,
                                                               PRIMARY KEY (`id`),
                                                               INDEX `fk_products_images_products1_idx` (`productId` ASC) VISIBLE,
                                                               INDEX `fk_products_images_images1_idx` (`imageId` ASC) VISIBLE,
                                                               CONSTRAINT `fk_products_images_products`
                                                                   FOREIGN KEY (`productId`)
                                                                       REFERENCES `kursach6_db`.`products` (`id`)
                                                                       ON DELETE NO ACTION
                                                                       ON UPDATE NO ACTION,
                                                               CONSTRAINT `fk_products_images_images`
                                                                   FOREIGN KEY (`imageId`)
                                                                       REFERENCES `kursach6_db`.`images` (`id`)
                                                                       ON DELETE NO ACTION
                                                                       ON UPDATE NO ACTION)
    ENGINE = InnoDB;

USE `kursach6_db`;

DELIMITER $$
USE `kursach6_db`$$
CREATE DEFINER = CURRENT_USER TRIGGER `kursach6_db`.`users_BEFORE_INSERT` BEFORE INSERT ON `users` FOR EACH ROW
BEGIN
    DECLARE msg VARCHAR(255);
    IF CURDATE() < NEW.birthDate
    THEN
        SET msg = 'Birthdate can''t be in future';
        SIGNAL SQLSTATE '45002' SET message_text = msg;
    END IF;
END$$

USE `kursach6_db`$$
CREATE DEFINER = CURRENT_USER TRIGGER `kursach6_db`.`products_AFTER_INSERT` AFTER INSERT ON `products` FOR EACH ROW
BEGIN
    INSERT INTO `inventory` (`amount`, `productId`) VALUES (0, NEW.id);
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
